/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as StationsRouteImport } from './routes/stations'
import { Route as AnomaliesIndexRouteImport } from './routes/anomalies.index'
import { Route as AnomaliesIdRouteImport } from './routes/anomalies.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsRoute = StationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesIndexRoute = AnomaliesIndexRouteImport.update({
  id: '/anomalies/',
  path: '/anomalies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesIdRoute = AnomaliesIdRouteImport.update({
  id: '/anomalies/$id',
  path: '/anomalies/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/sensors': typeof SensorsRoute
  '/stations': typeof StationsRoute
  '/anomalies/$id': typeof AnomaliesIdRoute
  '/anomalies/': typeof AnomaliesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/sensors': typeof SensorsRoute
  '/stations': typeof StationsRoute
  '/anomalies/$id': typeof AnomaliesIdRoute
  '/anomalies': typeof AnomaliesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/sensors': typeof SensorsRoute
  '/stations': typeof StationsRoute
  '/anomalies/$id': typeof AnomaliesIdRoute
  '/anomalies/': typeof AnomaliesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/sensors'
    | '/stations'
    | '/anomalies/$id'
    | '/anomalies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/sensors'
    | '/stations'
    | '/anomalies/$id'
    | '/anomalies'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/sensors'
    | '/stations'
    | '/anomalies/$id'
    | '/anomalies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  SensorsRoute: typeof SensorsRoute
  StationsRoute: typeof StationsRoute
  AnomaliesIdRoute: typeof AnomaliesIdRoute
  AnomaliesIndexRoute: typeof AnomaliesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations': {
      id: '/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof StationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies/': {
      id: '/anomalies/'
      path: '/anomalies'
      fullPath: '/anomalies/'
      preLoaderRoute: typeof AnomaliesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies/$id': {
      id: '/anomalies/$id'
      path: '/anomalies/$id'
      fullPath: '/anomalies/$id'
      preLoaderRoute: typeof AnomaliesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  SensorsRoute: SensorsRoute,
  StationsRoute: StationsRoute,
  AnomaliesIdRoute: AnomaliesIdRoute,
  AnomaliesIndexRoute: AnomaliesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
